tesseract:
  path: "/usr/bin/tesseract"  # Adjust to your Tesseract path
  lang: "eng+ind"            # OCR languages (English + Indonesian)
ocr:
  confidence_threshold: 0.6  # Confidence threshold for OCR results
templates:
  ktp:
    fields:
      province: "PROVINSI\\s*([A-Z\\s]+)"
      city: "(?:KABUPATEN|KOTA)\\s*([A-Z\\s]+)"
      nik: "NIK\\s*[:=]\\s*(\\d{16})"
      name: "Nama\\s*[:=]\\s*([A-Z\\s]+)"
      birth_place: "Tempat/Tgl Lahir\\s*[:=]\\s*([A-Z\\s]+),"
      birth_date: "Tempat/Tgl Lahir\\s*[:=][^0-9]*(\\d{2}-\\d{2}-\\d{4})"
      gender: "Jenis Kelamin\\s*[:=]\\s*([A-Z]+)"
      blood_type: "Gol\\.?\\s*Darah\\s*[:=]\\s*([A-Z0-9+-]+)"
      address: "Alamat\\s*[:=]\\s*([A-Z0-9\\s/.,-]+)"
      rt_rw: "RT/?RW\\s*[:=]\\s*([0-9\\s/-]+)"
      kelurahan_desa: "Kel/?Desa\\s*[:=]\\s*([A-Z\\s]+)"
      kecamatan: "Kecamatan\\s*[:=]\\s*([A-Z\\s]+)"
      religion: "Agama\\s*[:=]\\s*([A-Z\\s]+)"
      marital_status: "Status Perkawinan\\s*[:=]\\s*([A-Z\\s]+)"
      occupation: "Pekerjaan\\s*[:=]\\s*([A-Z\\s]+)"
      nationality: "Kewarganegaraan\\s*[:=]\\s*([A-Z\\s]+)"
      valid_until: "Berlaku Hingga\\s*[:=]\\s*([0-9\\-]+)"
